move home into config/home-dir

diff --git a/scripts/symlink-dotfiles b/scripts/symlink-dotfiles
--- a/scripts/symlink-dotfiles
+++ b/scripts/symlink-dotfiles
@@ -1,19 +1,29 @@
 #!/usr/bin/env bash
 
+#exit if any command fails
 set -e
+#ensure * includes hidden files
 shopt -s dotglob
 
 REPO="$HOME/dotfiles"
 mkdir -p "$HOME/.config"
 
-for f in "$REPO/home/"*; do
-    [ -e "$f" ] || continue
-    ln -snf "$f" "$HOME/$(basename "$f")"
-done
-
 for f in "$REPO/config/"*; do
+    #if f doesn't exist continue. Needed because bash treats empty directories wierd
     [ -e "$f" ] || continue
-    ln -snf "$f" "$HOME/.config/$(basename "$f")"
+
+    FILENAME=$(basename "$f")
+
+    # Check if the current item is a directory named 'home-dir'
+    if [ -d "$f" ] && [ "$FILENAME" == "home-dir" ]; then
+        for home_file in "$f/"*; do
+            #if $home_file doesn't exist continue. Needed because bash treats empty directories wierd
+            [ -e "$home_file" ] || continue
+            ln -snf "$home_file" "$HOME/$(basename "$home_file")"
+        done
+    else
+        ln -snf "$f" "$HOME/.config/$FILENAME"
+    fi
 done
 
-echo done
+echo "done"
